apiVersion: v1
baseDomain: dev.mindsparks.io 
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 0 # In upi, it'll be 0
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 3 
metadata:
  name: lab
networking:
  clusterNetwork:
  - cidr: 10.10.0.0/16 
    hostPrefix: 23 
  networkType: OVNKubernetes 
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: ''
sshKey: '' 
