apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolume
metadata:
  name: local-nvme-storage
  namespace: openshift-local-storage
spec:
  logLevel: Normal
  managementState: Managed
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: Exists
  storageClassDevices:
    - storageClassName: local-odf-nvme
      volumeMode: Block
      fsType: ""
      devicePaths:
        - /dev/nvme0n1
        - /dev/nvme1n1
        - /dev/nvme2n1
        - /dev/nvme3n1
        - /dev/nvme4n1
        - /dev/nvme5n1
        - /dev/nvme6n1
        - /dev/nvme7n1
        - /dev/nvme8n1
        - /dev/nvme9n1
        - /dev/nvme10n1
        - /dev/nvme11n1